# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore,QtGui,QtWidgets

import chatgpt1
# import clickdu
import pyqt
import cv2


class Ui_Form(object):
    def setupUi(self,Form):
        self.Form = Form
        self.Form.setObjectName("Form")
        # Form.setEnabled(True)
        Form.resize(1024,600)
        # Form.setMaximumSize(QtCore.QSize(16777215,501))
        Form.setStyleSheet("QWidget{\n"
                           "    background-color:white;\n"
                           "}")
        self.bcg = QtWidgets.QFrame(Form)
        self.bcg.setGeometry(QtCore.QRect(110, 0, 621, 351))
        self.bcg.setStyleSheet("image: url(./demo_gifs/书桌.png);")
        self.bcg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bcg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bcg.setObjectName("bcg")
        self.zuozi = QtWidgets.QPushButton(Form)
        self.zuozi.setGeometry(QtCore.QRect(20, 20, 71, 71))
        self.zuozi.setStyleSheet("QPushButton{\n"
                                      "    background:rgb(255, 217, 254);\n"
                                      "    font: 9pt \"黑体\";\n"
                                      "}")
        self.zuozi.setObjectName("pushButton")

        self.wenda = QtWidgets.QPushButton(Form)
        self.wenda.setGeometry(QtCore.QRect(30, 390, 151, 71))
        self.wenda.setStyleSheet("QPushButton{\n"
                                        "    background:rgb(189, 49, 36);\n"
                                        "    font-size:25px;\n"
                                        "}")
        self.wenda.setObjectName("pushButton_2")

        self.diandu = QtWidgets.QPushButton(Form)
        self.diandu.setGeometry(QtCore.QRect(240, 390, 161, 71))
        self.diandu.setStyleSheet("QPushButton{\n"
                                        "    background:rgb(255, 248, 29);\n"
                                        "    font-size:25px;\n"
                                        "}")
        self.diandu.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.diandu.setObjectName("pushButton_3")

        self.jiazhang = QtWidgets.QPushButton(Form)
        self.jiazhang.setGeometry(QtCore.QRect(670, 390, 151, 71))
        self.jiazhang.setStyleSheet("QPushButton{\n"
                                        "    background:rgb(170, 255, 127);\n"
                                        "    font-size:25px;\n"
                                        "}")
        self.jiazhang.setObjectName("pushButton_4")

        self.jihua = QtWidgets.QPushButton(Form)
        self.jihua.setGeometry(QtCore.QRect(460, 390, 151, 71))
        self.jihua.setStyleSheet("QPushButton{\n"
                                        "    background:rgb(64, 149, 229);\n"
                                        "    font-size:25px;\n"
                                        "}")
        self.jihua.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.zuozi.clicked.connect(self.openzuozi)
        self.wenda.clicked.connect(self.openwenda)
        self.diandu.clicked.connect(self.opendiandu)
    #     缺交流、计划

    def openzuozi(self):
        self.ui2 = pyqt.Example()
        self.ui2.show()

    def openwenda(self):
        self.ui4 = chatgpt.Ui_Form()
        self.mainWindow4 = QMainWindow()
        self.ui4.setupUi(self.mainWindow4)
        self.mainWindow4.show()

    def opendiandu(self):
        self.ui3 = clickdu.Ui_Form()
        self.mainWindow3 = QMainWindow()
        self.ui3.setupUi(self.mainWindow3)
        self.mainWindow3.show()

    def retranslateUi(self,Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form","主界面"))
        self.zuozi.setText(_translate("Form","坐姿检测"))
        self.wenda.setText(_translate("Form","智能问答"))
        self.diandu.setText(_translate("Form","智能点读"))
        self.jihua.setText(_translate("Form", "学习计划"))
        self.jiazhang.setText(_translate("Form", "家长交流"))

import sys
from PyQt5.QtWidgets import QApplication,QMainWindow

if __name__ == '__main__':
    # 只有直接运行这个脚本，才会往下执行
    # 别的脚本文件执行，不会调用这个条件句

    # 实例化，传参
    app = QApplication(sys.argv)

    # 创建对象
    mainWindow = QMainWindow()

    # 创建ui，引用demo1文件中的Ui_MainWindow类
    ui = Ui_Form()
    # 调用Ui_MainWindow类的setupUi，创建初始组件
    ui.setupUi(mainWindow)
    # 创建窗口
    mainWindow.show()
    # 进入程序的主循环，并通过exit函数确保主循环安全结束(该释放资源的一定要释放)
    sys.exit(app.exec_())
